#******************************************************************************
#
# Makefile - A convenience makefile for internal use building IQmath.
#
# Copyright (c) 2010 Texas Instruments Incorporated.  All rights reserved.
# TI Information - Selective Disclosure
#
#******************************************************************************

all:
	@make -f Makefile.IQmathLib

clean:
	@make -f Makefile.IQmathLib clean

realclean:
	@make -f Makefile.IQmathLib realclean
	@make -f Makefile.lmi clean
